version: '3.3'
services:
  couchbase:
    image: couchbase:enterprise-6.0.2
    ports:
      - '8091-8096:8091-8096'
      - '11210-11211:11210-11211'
    volumes:
      - ./couchbase/local_data:/opt/couchbase/var